/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package demo

class AppTest extends GroovyTestCase {
    void testGreeting() {
        def app = new App()

        def result = app.greeting

        assert result != null
        assert 1==2
    }
}
